apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-barnes
  labels:
    name: parsec-barnes
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:splash2x_barnes
        name: parsec-barnes
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "./run -a run -S splash2x -p barnes -i native -n 7"]
        resources:
          requests:
            cpu: "6"
            memory: "1Gi"
          limits:
            cpu: "7"
            memory: "31Gi"
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-a-8core"
